site_name: Georgia Tech Big Data Analytics Bootcamp

nav:
  - Home: index.md
  - Python Introduction:
    - Python for Data Analysis: 001-python.md
  - Environment Setup:
    - Docker: 002-docker.md
    - Zeppelin: 003-zeppelin.md
  - Scala and Spark:
    - Scala Basics: 004-scala.md
    - Spark Basics: 005-spark.md


theme: readthedocs

markdown_extensions:
  - admonition

extra_css: [extra.css]
